#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c holm<tab>/bo<tab>
#
# ...to quickly jump into holman/boom, for example.
#
# This also accounts for how Go structures its projects. For example, it will
# autocomplete both on $PROJECTS, and also assume you want to autocomplete on
# your Go projects in $GOPATH/src.

if { [ -n "$TMUX_PANE" ]; } then
  # not in tmux pane
  tmux new-window -n $1
  tmux send-keys "cd $PROJECTS/$1" C-m
  tmux send-keys "vim" C-m


  tmux split-window -v -p 30
  tmux send-keys "cd $PROJECTS/$1" C-m
  tmux split-window -h -p 50
  tmux send-keys "cd $PROJECTS/$1" C-m

  tmux select-pane -t 2
else
  cd $PROJECTS/$1
fi
